### ISSUE TITLE
Create CEL variables for well known issuers

### ISSUE THREAD

**Issue by verbanicm** [abcxyz/github-token-minter#134]
### TL;DR

Prevent mistakes by providing CEL variables for well known OIDC token issuers.

### Detailed design

Instead of:
`assertion.iss == 'https://token.actions.githubusercontent.com'`

Add variables so the syntax becomes:

`assertion.iss == issuers.github`

**Comment by bradegler** [comment]
@Celdir - has this issue been completed?

**Comment by Celdir** [comment]
Yep, this is done. Closing now
